### ISSUE TITLE
[BUG] Multiplier permissions don't take effect until server restart

### ISSUE THREAD

**Issue by kohle** [PluginBugs/Issues-RPGMoney#13]
**Describe the bug**
When different groups are assigned a multiply and a user is changed groups, they will not be able to use the multiplier until the next full restart. It doesn't work even after a full reload (I know you should never reload, did it just to test this bug!), you must restart.

**To Reproduce**
1. Have at least two groups in your permissions plugin (I'm using LuckPerms 5.3.47), each with different multipliers. I have Group 1 with no multiplier (just `rpgmoney.drop.blockbreak` and `rpgmoney.pickup`). Group 2 inherits those permissions, and has `rpgmoney.multiply.drop.10`
2. Make sure the player is in Group 1, and then update their group to Group 2.

**Expected behavior**
Expected behavior is to immediately get the multiplier permission applied, but they don't until the full restart.

**Info (please complete the following information):**
 - Server version: Paper 1.17.1 #279
 - Client version: Vanilla 1.17.1
 - Plugin version: 1.1.31

**Additional context**
There also seems to be an issue with the `multiply` and `drop` multipliers together. Just for testing, I gave both a pickup and a drop multiplier of 10 but only the pickup multiplier worked, the drops were still at base level. I can't think of a use case for having both applied at once, but perhaps it would cause issues through the way groups can inherit permissions?

As always, appreciate your work and fast support 😃

**Comment by LoneDev6** [comment]
> they will not be able to use the multiplier until the next full restart

In the next update there will be no need to restart, the permission will be always up to date with the plugin functionality itself.

> There also seems to be an issue with the `multiply` and `drop` multipliers together. Just for testing, I gave both a pickup and a drop multiplier of 10 but only the pickup multiplier worked, the drops were still at base level.

I didn't test with the 1.1.31 version but the new update doesn't have this problem, if you add both permissions you will see the drop multiplied and then also the pickup (btw it really has no real sense to apply both permissions in a normal server XD ). I recoded the multipliers logic, now you will have to create new "group" in the configuration file, then you'll be able to use them in the permission system.

For example this is the default list of groups in config.yml
```yml
multipliers_groups:
  drop:
    "1": 1
    "2": 2
    "3": 3
    "4": 4
    "5": 5
    "10": 10
  pickup:
    "1": 1
    "2": 2
    "3": 3
    "4": 4
    "5": 5
    "10": 10
```
which allows you to set these permissions:
```
rpgmoney.multiply.drop.1
rpgmoney.multiply.drop.2
rpgmoney.multiply.drop.2
rpgmoney.multiply.drop.4
rpgmoney.multiply.drop.5
rpgmoney.multiply.drop.10
```
```
rpgmoney.multiply.pickup.1
rpgmoney.multiply.pickup.2
rpgmoney.multiply.pickup.2
rpgmoney.multiply.pickup.4
rpgmoney.multiply.pickup.5
rpgmoney.multiply.pickup.10
```

(this change was made to be able to have good performance because now I have to check each time if the player has permission. Before this update I used to cache the result to avoid excessive processing).
